site_name: Nil Monfort
site_url: https://nilmonfort.com
#repo_url: https://github.com/nilmonfort/nilmonfort-blog
theme:
  name: material
  logo: assets/images/logo.svg
  favicon: assets/images/logo.svg
  custom_dir: docs/overrides
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.indexes
    # - toc.integrate   # keep OFF for proper sidebar alignment
    - toc.follow
    - content.code.copy
    #- content.action.edit
    - content.tabs.link
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: black
      accent: blue
      toggle:
        icon: material/weather-night
        name: Dark mode
    - scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Light mode
  font:
    text: Inter
    code: JetBrains Mono

plugins:
  - search
  - blog:
      blog_dir: writing
      post_dir: "{blog}/posts"
      archive: true
      archive_name: Archive
      archive_url_date_format: yyyy
      categories: true
      categories_name: Categories
      authors_file: writing/authors.yml
      pagination_per_page: 10
      post_excerpt_separator: "<!-- more -->"
      post_excerpt: required  # fail build if post missing excerpt
  - tags
  - rss:
      match_path: writing/.*        # only posts
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Writing:
    - writing/index.md
    - Tags: writing/tags.md
  #- Projects: projects.md
  - Resume: resume.md
  - About: about.md

extra:
  social:
    - icon: fontawesome/solid/envelope
      link: mailto:nilmonfort98@gmail.com
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/nil-monfort-761660213/
    - icon: fontawesome/brands/github
      link: https://github.com/nilm9
  generator: false   # hide footer generator text

extra_css:
  - assets/css/overrides.css
