name: Deploy MkDocs
on:
  workflow_dispatch: {} 
  #push:
  #  branches: [ main ]
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: echo "----- mkdocs.yml on CI -----" && cat mkdocs.yml
      - run: echo "----- Checking for tags_file -----" && grep -n "tags_file" mkdocs.yml || echo "No tags_file found"
      - run: mkdocs build --strict
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site